# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_auto_20170424_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_privileges',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grant_dbtag', models.CharField(max_length=30)),
                ('grant_user', models.CharField(max_length=20)),
                ('grant_ip', models.CharField(max_length=15)),
                ('grant_privileges', models.CharField(max_length=300)),
                ('grant_db', models.CharField(max_length=20)),
                ('grant_tables', models.CharField(max_length=1000)),
                ('grant_user_pwd', models.CharField(max_length=80)),
                ('grant_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('modify_date', models.DateTimeField(auto_now_add=True)),
                ('grant_status', models.SmallIntegerField(default=1)),
                ('grant_comment', models.CharField(max_length=200)),
                ('db_name', models.ForeignKey(on_delete=models.SET('deleted'), to='myapp.Db_name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user_profile',
            options={'permissions': (('can_mysql_query', 'can see mysql_query view'), ('can_log_query', 'can see log_query view'), ('can_see_execview', 'can see mysql exec view'), ('can_see_inception', 'can see inception view'), ('can_see_metadata', 'can see meta_data view'), ('can_see_mysqladmin', 'can see mysql_admin view'), ('can_export', 'can export csv'), ('can_insert_mysql', 'can insert mysql'), ('can_update_mysql', 'can update mysql'), ('can_delete_mysql', 'can delete mysql'), ('can_create_mysql', 'can create mysql'), ('can_drop_mysql', 'can drop mysql'), ('can_truncate_mysql', 'can truncate mysql'), ('can_alter_mysql', 'can alter mysql'), ('can_query_mongo', 'can query mongo'), ('can_see_taskview', 'can see task view'), ('can_admin_task', 'can admin task'), ('can_delete_task', 'can delete task'), ('can_update_task', 'can update task'), ('can_query_pri', 'can query pri'), ('can_set_pri', 'can set pri'), ('can_oper_saltapi', 'can oper saltapi'), ('can_grant_db', 'can grant db'))},
        ),
    ]
