# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_auto_20171130_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_privileges',
            old_name='grant_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='db_privileges',
            old_name='modify_date',
            new_name='modify_modify',
        ),
    ]
