# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_auto_20171204_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_privileges',
            old_name='modify_modify',
            new_name='modify_time',
        ),
        migrations.AlterField(
            model_name='db_priv_log',
            name='fkid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Db_privileges'),
        ),
    ]
