# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_auto_20171204_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_priv_log',
            name='fkid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Db_privileges'),
        ),
    ]
