# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_auto_20171205_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_account',
            name='tags',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='ip',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='db_priv_log',
            name='fkid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Db_privileges'),
        ),
    ]
