# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0047_auto_20171208_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Db_user_pwd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='db_priv_log',
            name='fkid',
            field=models.ForeignKey(on_delete=models.SET('deleted'), to='myapp.Db_privileges'),
        ),
    ]
