# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_auto_20171211_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_priv_log',
            name='fkid',
            field=models.ForeignKey(on_delete=models.SET('deleted'), to='myapp.Db_privileges'),
        ),
    ]
