# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_auto_20171220_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_priv_log',
            name='fkid',
            field=models.ForeignKey(on_delete=models.SET('deleted'), to='myapp.Db_privileges'),
        ),
        migrations.AlterField(
            model_name='db_privileges',
            name='grant_db',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='db_privileges',
            name='grant_dbtag',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='db_privileges',
            name='grant_ip',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='db_privileges',
            name='grant_user',
            field=models.CharField(max_length=30),
        ),
    ]
