# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_auto_20171221_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_priv_log',
            name='fkid',
            field=models.ForeignKey(on_delete=models.SET('deleted'), to='myapp.Db_privileges'),
        ),
        migrations.AlterField(
            model_name='db_privileges',
            name='grant_db',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='db_privileges',
            name='grant_ip',
            field=models.CharField(max_length=200),
        ),
    ]
