# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_auto_20171222_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_name',
            name='dbtag',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='db_priv_log',
            name='fkid',
            field=models.ForeignKey(on_delete=models.SET('deleted'), to='myapp.Db_privileges'),
        ),
    ]
