# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_auto_20171222_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_priv_log',
            name='priv_status',
            field=models.CharField(default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='db_priv_log',
            name='fkid',
            field=models.ForeignKey(on_delete=models.SET('-1'), to='myapp.Db_privileges'),
        ),
        migrations.AlterField(
            model_name='db_privileges',
            name='db_name',
            field=models.ForeignKey(on_delete=models.SET('-1'), to='myapp.Db_name'),
        ),
    ]
